const studentMenuBtn=document.getElementById("studentMenuBtn"),studentNav=document.getElementById("studentNav"),studentNavBackdrop=document.getElementById("studentNavBackdrop");
function setStudentNav(open){document.body.classList.toggle("student-nav-open",open);document.body.style.overflow=open?"hidden":"";studentMenuBtn?.setAttribute("aria-expanded",String(open));studentMenuBtn?.setAttribute("aria-label",open?"Close student navigation":"Open student navigation");studentNav?.setAttribute("aria-hidden",String(!open));studentNav?.toggleAttribute("inert",!open);studentNavBackdrop?.setAttribute("aria-hidden",String(!open));}
studentMenuBtn?.addEventListener("click",()=>setStudentNav(!document.body.classList.contains("student-nav-open")));studentNavBackdrop?.addEventListener("click",()=>setStudentNav(false));studentNav?.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>setStudentNav(false)));document.addEventListener("keydown",e=>{if(e.key==="Escape")setStudentNav(false)});window.addEventListener("resize",()=>{if(window.innerWidth>960)setStudentNav(false)});

const state={announcement:{items:[],page:0},classinfo:{items:[],page:0}};const PAGE_SIZE=3;
function formatDate(v){if(!v)return"—";return new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric",hour:"numeric",minute:"2-digit"}).format(new Date(v))}
function openViewer(item,type){document.getElementById("viewerKicker").textContent=type==="announcement"?"ANNOUNCEMENT":"CLASS INFORMATION";document.getElementById("viewerTitle").textContent=item.title||"Untitled";document.getElementById("viewerDate").textContent=formatDate(item.updated_at||item.created_at);document.getElementById("viewerBody").textContent=item.body||"";const v=document.getElementById("contentViewer");v.classList.remove("hidden");v.setAttribute("aria-hidden","false");document.body.style.overflow="hidden";}
function closeViewer(){const v=document.getElementById("contentViewer");v.classList.add("hidden");v.setAttribute("aria-hidden","true");if(!document.body.classList.contains("student-nav-open"))document.body.style.overflow="";}
document.querySelectorAll("[data-close-viewer]").forEach(x=>x.addEventListener("click",closeViewer));document.addEventListener("keydown",e=>{if(e.key==="Escape")closeViewer()});
function renderPaged(type){const cfg=state[type],feed=document.getElementById(type==="announcement"?"announcementFeed":"classInfoFeed"),pageEl=document.getElementById(type==="announcement"?"announcementPage":"classInfoPage"),prev=document.getElementById(type==="announcement"?"announcementPrev":"classInfoPrev"),next=document.getElementById(type==="announcement"?"announcementNext":"classInfoNext");const totalPages=Math.max(1,Math.ceil(cfg.items.length/PAGE_SIZE));cfg.page=Math.min(cfg.page,totalPages-1);const start=cfg.page*PAGE_SIZE;const visible=cfg.items.slice(start,start+PAGE_SIZE);feed.innerHTML="";if(!visible.length){const e=document.createElement("div");e.className="content-empty";e.textContent=type==="announcement"?"No published announcements yet.":"No published class information yet.";feed.appendChild(e)}else visible.forEach((item,i)=>{const card=document.createElement("article");card.className="content-card";const marker=document.createElement("div");marker.className="content-marker";marker.textContent=String(start+i+1).padStart(2,"0");const copy=document.createElement("div");copy.className="content-copy";const meta=document.createElement("div");meta.className="content-meta";meta.textContent=formatDate(item.updated_at||item.created_at);const title=document.createElement("h3");title.textContent=item.title||"Untitled";const preview=document.createElement("p");preview.textContent=item.body||"";copy.append(meta,title,preview);const view=document.createElement("button");view.className="content-view-btn";view.type="button";view.textContent="Read";view.addEventListener("click",()=>openViewer(item,type));card.append(marker,copy,view);feed.appendChild(card)});pageEl.textContent=`${cfg.items.length?cfg.page+1:1} / ${totalPages}`;prev.disabled=cfg.page<=0;next.disabled=cfg.page>=totalPages-1;}
function bindPager(type){const prev=document.getElementById(type==="announcement"?"announcementPrev":"classInfoPrev"),next=document.getElementById(type==="announcement"?"announcementNext":"classInfoNext");prev.addEventListener("click",()=>{if(state[type].page>0){state[type].page--;renderPaged(type)}});next.addEventListener("click",()=>{if((state[type].page+1)*PAGE_SIZE<state[type].items.length){state[type].page++;renderPaged(type)}})}
bindPager("announcement");bindPager("classinfo");
async function loadContent(){const [a,c]=await Promise.all([supabaseClient.from("announcements").select("id,title,body,published,created_at,updated_at").eq("published",true).order("updated_at",{ascending:false}),supabaseClient.from("class_information").select("id,title,body,published,created_at,updated_at").eq("published",true).order("updated_at",{ascending:false})]);if(a.error){console.error(a.error);document.getElementById("announcementFeed").innerHTML='<div class="content-error">Unable to load announcements right now.</div>'}else{state.announcement.items=a.data||[];document.getElementById("announcementCount").textContent=`${state.announcement.items.length} published`;renderPaged("announcement")}if(c.error){console.error(c.error);document.getElementById("classInfoFeed").innerHTML='<div class="content-error">Unable to load class information right now.</div>'}else{state.classinfo.items=c.data||[];document.getElementById("classInfoCount").textContent=`${state.classinfo.items.length} published`;renderPaged("classinfo")}}
let homeInitPromise=null;let lastHomeInit=0;const HOME_REFRESH_MS=30000;
async function initHome(){if(homeInitPromise)return homeInitPromise;if(Date.now()-lastHomeInit<HOME_REFRESH_MS)return;homeInitPromise=(async()=>{const {data:{session}={}}=await supabaseClient.auth.getSession();if(!session){window.location.replace("../login/index.html");return}const {data:student,error}=await supabaseClient.from("students").select("student_no,full_name,gmail,avatar_url").eq("auth_user_id",session.user.id).maybeSingle();if(error){console.error(error);document.getElementById("studentName").textContent="Unable to load profile";return}if(!student){window.location.replace("../registrar/index.html");return}const name=student.full_name||session.user.user_metadata?.full_name||session.user.user_metadata?.name||"Student";document.getElementById("welcomeName").textContent=name.split(/\s+/)[0];document.getElementById("studentName").textContent=name;document.getElementById("studentNo").textContent=`Student No. ${student.student_no||"—"}`;document.getElementById("studentEmail").textContent=student.gmail||session.user.email||"—";const img=document.getElementById("avatar");const fallback=`https://ui-avatars.com/api/?name=${encodeURIComponent(name)}&background=111827&color=ffffff&size=180`;img.src=student.avatar_url?`${student.avatar_url}${student.avatar_url.includes("?")?"&":"?"}v=${Date.now()}`:fallback;img.onerror=()=>{img.src=fallback};const info=await BSISAdmin.apply();document.getElementById("adminHomeProfileBadge")?.classList.toggle("hidden",!info.isAdmin);await loadContent();lastHomeInit=Date.now()})().catch(error=>{console.error(error);document.querySelectorAll(".content-loading").forEach(el=>{el.textContent="Unable to load portal data right now."})}).finally(()=>{homeInitPromise=null});return homeInitPromise}
document.getElementById("signOutBtn")?.addEventListener("click",async()=>{await supabaseClient.auth.signOut();window.location.replace("../login/index.html")});window.addEventListener("pageshow",initHome);document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="visible")initHome()});
